### ISSUE TITLE
Dump on exception based on filter

### ISSUE THREAD

**Issue by naveensrinivasan** [goldshtn/minidumper#4]
This might be not be the part of this tool. But often memory dumps are collected when exceptions are raised. 

If this tool could capture memory dump when an unhandled exception is raised ,similar to procdump it would be cool.

**Comment by lowleveldesign** [comment]
@naveensrinivasan I added this feature and the pull request is awaiting. In the meantime you may have a look at my fork: https://github.com/lowleveldesign/minidumper/releases/tag/v2.0 and a post: https://lowleveldesign.wordpress.com/2015/12/21/new-features-coming-to-minidumper/

**Comment by naveensrinivasan** [comment]
@lowleveldesign Thanks!

**Comment by lowleveldesign** [comment]
It is now in the master branch.
