### ISSUE TITLE
tried use -l and -t arguments both at time.

### ISSUE THREAD

**Issue by kishanAnem** [goldshtn/minidumper#7]
@goldshtn  @lowleveldesign  trying learn about minidumper. tried -l and -t arguments both at time. in my target process added debug and trace writeline method, to log some message. but it crashed. please let me is it right way to do. 

my code in target process.

            Trace.WriteLine("Trace.WriteLine");
            Debug.WriteLine("Debug.WriteLine");

            Console.WriteLine("Press the Enter key to exit the program at any time... ");
            Console.ReadLine();
command line : 
            `MiniDumper.exe -mh -t -x C:\Users\kishan\Desktop             
 C:\Users\kishan\source\repos\MemoryThreshhold\MemoryThreshhold\bin\Debug\MemoryThreshhold.exe`
![minidumper](https://user-images.githubusercontent.com/8208927/34521345-4bab7178-f0b3-11e7-8132-5fd2565e68f2.PNG)
![minidumper1](https://user-images.githubusercontent.com/8208927/34521346-4be0988a-f0b3-11e7-8a7f-385c9173accd.PNG)
![minidumper2](https://user-images.githubusercontent.com/8208927/34521347-4c1821ba-f0b3-11e7-99ee-e0ad60a91515.PNG)
![minidumper3](https://user-images.githubusercontent.com/8208927/34521348-4c50e770-f0b3-11e7-9bb1-1e9755788f8d.PNG)
![minidumper4](https://user-images.githubusercontent.com/8208927/34521350-4c83a764-f0b3-11e7-9cfa-303c0b0d1349.PNG)

**Comment by lowleveldesign** [comment]
Hi @kishan3034, did minidumper make the dump? I don't see the crush information in the console output you provided - do you have a Windows Error Reporting report or any information about the error that occurred? Also, when you run a command line application under minidumper consider using **-c** switch to open a new command line window (sometimes there are problems with the shared console). 

I will check later today or tomorrow why the Trace messages do not appear in the output.

**Comment by kishanAnem** [comment]
it made a dump. opened a dump in vs, it shows no compatible code is running. uploaded log file and dump file.
[minidumperlog.txt](https://github.com/goldshtn/minidumper/files/1600858/minidumperlog.txt) 
[MemoryThreshhold_180103_211554.zip](https://github.com/goldshtn/minidumper/files/1600969/MemoryThreshhold_180103_211554.zip)

**Comment by kishanAnem** [comment]
Hi @lowleveldesign and @goldshtn , In Debugger.cs WaitForDebugEvents method didn't find following event.

`                               case DEBUG_EVENT_CODE.OUTPUT_DEBUG_STRING_EVENT:
                                var debugString = debugEvent.Value.DebugString;
                                miniDumper.DebugString(debugString);
                                break;`
I've written some code. I will complete. if i'm not wrong, shall I work on it.

**Comment by lowleveldesign** [comment]
@kishan3034 I opened the dump you sent in both Visual Studio (2017 Enterprise 15.5.2) and WinDbg with no problems. The error you receive looks like a bitness problem, but it would be strange. Could you try opening it in the latest VS?

And you are right that there is a missing case statement in minidumper (and that's the reason for missing debug output). I will fix it in the coming days and will make a new release. I will later ask @goldshtn to merge the changes. Great thanks!

**Comment by kishanAnem** [comment]
hi @goldshtn and @lowleveldesign, shall i fix this? already wrote code working fine and need to work on command line args. am willing to work with @lowleveldesign if it is ok with you.

**Comment by lowleveldesign** [comment]
@kishan3034 if you have the code please make a pull request to my fork (https://github.com/lowleveldesign/minidumper) - we will work on it there, I will create a release, and later pull request with your changes and mine (I have also some pending fixes in my fork) in the main repo.

**Comment by kishanAnem** [comment]
Sure will do. Thanks ☺️

**Comment by kishan3034** [comment]
Thanks ☺️

**Comment by goldshtn** [comment]
@lowleveldesign I sent you a collaboration invite, if you prefer to work directly on this repo it seems more straightforward to me.

**Comment by lowleveldesign** [comment]
@goldshtn great, thanks! I will soon add few pending fixes :) 

@kishan3034, you may create the pull request in this repo if you wish.
